//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinav_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunBilgileri
    {
        public int Id { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<decimal> BirimFiyat { get; set; }
        public Nullable<int> StokMiktari { get; set; }
    }
}
